version: '2'

services:
  ap:
    container_name: robert-app
    depends_on:
      - mongodb
    image: ${docker.repository.name}:${project.version}
    volumes:
      - $PWD/logs:/root/logs
    environment:
      - MONGO_URL=mongodb
      - EXTRA_OPTS="--lower_case_table_names=1"
      - TZ=Asia/Taipei
    ports: 
      - "8080:8080"    
  mongodb:
    container_name: robert-mongodb
    restart: always
    image: mongo:latest
    ports:
      - "27017:27017"    
    volumes:
      - data/mongodb:/data/db
    environment:
      - MONGODB_DATABASE=ec  
  cacti:
    image: "smcline06/cacti"
    depends_on:
      - rdbms
    ports:
        - "80:80"
        - "443:443"
    environment:
        - DB_NAME=cacti_master
        - DB_USER=cactiuser
        - DB_PASS=cactipassword
        - DB_HOST=db
        - DB_PORT=3306
        - DB_ROOT_PASS=rootpassword
        - INITIALIZE_DB=1
        - TZ=America/Los_Angeles
    links:
        - rdbms
  rdbms:
    image: "percona:5.7.14"
    ports:
      - "3306:3306"
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --max_connections=200
      - --max_heap_table_size=128M
      - --max_allowed_packet=32M
      - --tmp_table_size=128M
      - --join_buffer_size=128M
      - --innodb_buffer_pool_size=1G
      - --innodb_doublewrite=OFF
      - --innodb_flush_log_at_timeout=3
      - --innodb_read_io_threads=32
      - --innodb_write_io_threads=16
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - TZ=Asia/Taipei